/*
 * Estuary API
 *
 * This is the API for the Estuary application.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct MainEstimateDealBody {
    #[serde(rename = "durationBlks", skip_serializing_if = "Option::is_none")]
    pub duration_blks: Option<i32>,
    #[serde(rename = "replication", skip_serializing_if = "Option::is_none")]
    pub replication: Option<i32>,
    #[serde(rename = "size", skip_serializing_if = "Option::is_none")]
    pub size: Option<i32>,
    #[serde(rename = "verified", skip_serializing_if = "Option::is_none")]
    pub verified: Option<bool>,
}

impl MainEstimateDealBody {
    pub fn new() -> MainEstimateDealBody {
        MainEstimateDealBody {
            duration_blks: None,
            replication: None,
            size: None,
            verified: None,
        }
    }
}


