/*
 * Estuary API
 *
 * This is the API for the Estuary application.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct MainImportDealBody {
    #[serde(rename = "collection", skip_serializing_if = "Option::is_none")]
    pub collection: Option<String>,
    #[serde(rename = "collectionPath", skip_serializing_if = "Option::is_none")]
    pub collection_path: Option<String>,
    #[serde(rename = "dealIDs", skip_serializing_if = "Option::is_none")]
    pub deal_ids: Option<Vec<i32>>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

impl MainImportDealBody {
    pub fn new() -> MainImportDealBody {
        MainImportDealBody {
            collection: None,
            collection_path: None,
            deal_ids: None,
            name: None,
        }
    }
}


