/*
 * Estuary API
 *
 * This is the API for the Estuary application.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct MainAddContentToCollectionParams {
    #[serde(rename = "cids", skip_serializing_if = "Option::is_none")]
    pub cids: Option<Vec<String>>,
    #[serde(rename = "collection", skip_serializing_if = "Option::is_none")]
    pub collection: Option<String>,
    #[serde(rename = "contents", skip_serializing_if = "Option::is_none")]
    pub contents: Option<Vec<i32>>,
}

impl MainAddContentToCollectionParams {
    pub fn new() -> MainAddContentToCollectionParams {
        MainAddContentToCollectionParams {
            cids: None,
            collection: None,
            contents: None,
        }
    }
}


