/*
 * Estuary API
 *
 * This is the API for the Estuary application.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct MainUserStatsResponse {
    #[serde(rename = "numPins", skip_serializing_if = "Option::is_none")]
    pub num_pins: Option<i32>,
    #[serde(rename = "totalSize", skip_serializing_if = "Option::is_none")]
    pub total_size: Option<i32>,
}

impl MainUserStatsResponse {
    pub fn new() -> MainUserStatsResponse {
        MainUserStatsResponse {
            num_pins: None,
            total_size: None,
        }
    }
}


